version: 0.0
os: linux

files:
  - source: /
    destination: ~/AWSProject

hooks:
  ApplicationStop:
    - location: Scripts/ApplicationStop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: Scripts/BeforeInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: Scripts/ApplicationStart.sh
      timeout: 300
      runas: root
