version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/AWSProject
    overwrite: true

hooks:
  ApplicationStop:
    - location: Scripts/ApplicationStop.sh
      timeout: 180
  BeforeInstall:
    - location: Scripts/BeforeInstall.sh
      timeout: 180
  ApplicationStart:
    - location: Scripts/ApplicationStart.sh
      timeout: 180
