version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/AWSProject

hooks:
  ApplicationStop:
    - location: Scripts/ApplicationStop.sh
      timeout: 300
  BeforeInstall:
    - location: Scripts/BeforeInstall.sh
      timeout: 300
  ApplicationStart:
    - location: Scripts/ApplicationStart.sh
      timeout: 300
